# -*- coding: utf-8 -*-
"""AI Conversational Database Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ek-u4mt7SuvdiBIbxoHB2VCNO_BPm9jg
"""

!pip install -q openai


import sqlite3
from openai import OpenAI
from datetime import datetime


client = OpenAI(
    api_key=""
)

conn = sqlite3.connect("chatbot.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS chats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_message TEXT,
    bot_response TEXT,
    timestamp TEXT
)
""")

conn.commit()

def chatbot(user_input):

    response = client.chat.completions.create(
        model="gpt-4.1-mini",
        messages=[
            {
                "role": "system",
                "content": "You are a helpful AI assistant."
            },
            {
                "role": "user",
                "content": user_input
            }
        ]
    )

    bot_reply = response.choices[0].message.content

    # Save Chat in Database
    cursor.execute("""
    INSERT INTO chats (user_message, bot_response, timestamp)
    VALUES (?, ?, ?)
    """, (
        user_input,
        bot_reply,
        str(datetime.now())
    ))

    conn.commit()

    return bot_reply


print("🤖 AI Chatbot Started")
print("Type 'exit' to stop\n")

while True:

    user_input = input("You : ")

    if user_input.lower() == "exit":
        print("Chatbot Closed")
        break

    reply = chatbot(user_input)

    print("Bot :", reply)
    print()



print("\n===== CHAT HISTORY =====\n")

cursor.execute("SELECT * FROM chats")

rows = cursor.fetchall()

for row in rows:
    print("ID :", row[0])
    print("User :", row[1])
    print("Bot :", row[2])
    print("Time :", row[3])
    print("-" * 50)

conn.close()