# -*- coding: utf-8 -*-
"""AI Math Tutor use case.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1quV4nPuOD788-ivxLcPWbg4nfsCxdHqb
"""

import openai

openai.api_key = ""

chat_response = openai.chat.completions.create(
    model="gpt-3.5-turbo-16k",
    messages=[
        {"role": "system", "content": "you are an AI tutor that assists school students with math homework problems"},
        {"role": "user", "content":  "Help me solve the eqation 2x - 10 = 20 "},
        {"role": "assistant", "content": "try moving the 10 to the right hand side of the equation, what do you get?"},
        {"role": "user", "content":"x + 10 = 15"}
    ]
)
#extract only the text
print (chat_response.choices[0].message.content)

"""You are an AI tutor that assists schol students with math homework problems. You never reveal the right answer to the student. You ask probing questions to identify where the studengt might be needing help, provide hints and guideline and provide directional feedback to indicate if the student is mooving in the right direction"""

system_message ="You are an AI tutor that assists schol students with math homework problems. You never reveal the right answer to the student. You ask probing questions to identify where the studengt might be needing help, provide hints and guideline and provide directional feedback to indicate if the student is mooving in the right direction"
max_conversation = 20
conversation_length=0

message_history = [
    {"role": "system", "content": system_message},
    {"role": "system", "name": "example_user", "content": "Help me solve the equation 3x - 9 = 21."},
    {"role": "system", "name": "example_assistant", "content": "Sure! Try moving the 9 to the right hand side of the equation. What do you get?"},
    {"role": "system", "name": "example_user", "content": "3x = 12"},
    {"role": "system", "name": "example_assistant", "content": "Well, there seems to be a mistake. When you move 9 to the right hand side, you need to change its sign. Can you try again?"},
    {"role": "system", "name": "example_user", "content": "3x = 30"},
    {"role": "system", "name": "example_assistant", "content": "That looks good, great job! Now, try to divide both sides by 3. What do you get?"},
    {"role": "system", "name": "example_user", "content": "x = 10"},
    {"role": "user", "content": "Help me solve the equation x - 10 = 2x"}
]

while conversation_length < max_conversation:
    user_input = input()

    # exit if user enters exit
    if "exit" in user_input.lower():
        print("AI Tutor: Exiting the program")
        break

    message_history.append({"role": "user", "content": user_input})

    chat_response = openai.chat.completions.create(
        model="gpt-3.5-turbo-16k",
        messages=message_history
    ).choices[0].message.content

    print("\n", "AI Tutor:")
    print(chat_response)
    print("\n")

    message_history.append({"role": "assistant", "content": chat_response})  # add API response to message history
    conversation_length = conversation_length + 1  # another conversation done