# -*- coding: utf-8 -*-
"""Business Productivity Solutions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q9y9Li8gY1NezAuzE_KGzWn4FzGonIkm
"""

!pip install openai

from openai import OpenAI

client = OpenAI(api_key="")

def business_bot(prompt):
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "You are a powerful business productivity AI assistant. Help with emails, planning, marketing, automation, and business ideas."},
            {"role": "user", "content": prompt}
        ]
    )
    return response.choices[0].message.content

# Chat loop
while True:
    user = input("You: ")
    if user.lower() in ["exit", "quit"]:
        break
    print("Bot:", business_bot(user))