# -*- coding: utf-8 -*-
"""Hugging Face.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qNtf-J4WPnrtgwjNmElS3lSwRFZEKF5b
"""

!pip install datasets transformers[sentencepiece]

from transformers import pipeline #pipeline is a libuary which has all hugging face modals

classifier = pipeline("sentiment-analysis") # tell whethera sentence or comment is positive or negitive

classifier("FOOD is delicious")

classifier("I wiss food was good")

classifier ("Food is Delicious but ambience was not good")

classifier(["Food is Delicious","Food is Delicious but ambience was not good","I wish food was good",])

classifier("I am amazed by the speed of the processor but disappointed that it heats up quickly")

!pip install -U transformers

# @title
zero_shot = pipeline ("zero-shot-classification")  #zero-shot-classification is a library that our sentence belongs to which category

zero_shot("India won two bronze medals in pistol shooting",
          candidate_labels=['education','politics','business','sports']
)

zero_shot("This course is about Generative AI and we are learning about Hugging Face",
         candidate_labels=['education','politics','business'])

zero_shot("BJP is the largest party of the worls",
          candidate_labels=['education','politics','business'])

generator= pipeline("text-generation")

print(generator("Inthis course, we're gonna learn how to"))

#Use a pipeline as a high-level helper
from transformers import pipeline


pipe = pipeline("token-classification", model="dslim/bert-base-NER")

pipe("Asia is the lagerst continent")

pipe("Delhi is the capital of the india ")