# -*- coding: utf-8 -*-
"""Image Generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rhpG3A6FdNPaGqaKgYB99o5oXHdUWpOT
"""

!pip install -q openai pillow matplotli

from openai import OpenAI
from PIL import Image
import matplotlib.pyplot as plt
from io import BytesIO
import base64


client = OpenAI(
    api_key=""
)

def generate_image(prompt):

    try:

        response = client.images.generate(
            model="gpt-image-1",
            prompt=prompt,
            size="1024x1024"
        )


        image_data = response.data[0].b64_json


        image_bytes = base64.b64decode(image_data)


        img = Image.open(BytesIO(image_bytes))


        plt.figure(figsize=(8,8))
        plt.imshow(img)
        plt.axis("off")
        plt.show()

    except Exception as e:
        print("Error :", e)


print("🎨 AI Image Generation Bot")
print("Type 'exit' to stop\n")

while True:

    user_prompt = input("Enter Image Prompt : ")

    if user_prompt.lower() == "exit":
        print("Bot Closed")
        break

    generate_image(user_prompt)